// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luuycltyepeduyjelsub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1dXljbHR5ZXBlZHV5amVsc3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDAwNzMsImV4cCI6MjA2NDYxNjA3M30.jjaZKWHnFgq-pkHX8N2t4n3Ulf9uaHZ-BXu0Og5Ui24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);